version: '3.8'

services:
  redis:
    container_name: ytb_redis
    image: redis:7
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  ytb-gateway:
    container_name: ytb_gateway
    build: 
      context: ../ytb-gateway
      dockerfile: Dockerfile
    volumes:
      - ../ytb-gateway:/app
      - /app/.venv
      - /app/__pycache__
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DEBUG=1
      - ENV=development
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]

  ytb-fastwhisper:
    build:
      context: ../ytb-fastwhisper
      dockerfile: Dockerfile
    volumes:
      - ../ytb-fastwhisper:/app
      - /app/.venv
      - /app/__pycache__
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DEBUG=1
      - ENV=development
    ports:
      - "8001:8001"
    command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8001"]

  queue-worker:
    build:
      context: ../queue-worker
      dockerfile: Dockerfile
    volumes:
      - ../queue-worker:/app
      - /app/.venv
      - /app/__pycache__
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DEBUG=1
      - ENV=development
volumes:
  redis_data: 